// Code generated by MockGen. DO NOT EDIT.
// Source: infrastructure/unique_id_generator.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUniqueIdGenerator is a mock of UniqueIdGenerator interface.
type MockUniqueIdGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockUniqueIdGeneratorMockRecorder
}

// MockUniqueIdGeneratorMockRecorder is the mock recorder for MockUniqueIdGenerator.
type MockUniqueIdGeneratorMockRecorder struct {
	mock *MockUniqueIdGenerator
}

// NewMockUniqueIdGenerator creates a new mock instance.
func NewMockUniqueIdGenerator(ctrl *gomock.Controller) *MockUniqueIdGenerator {
	mock := &MockUniqueIdGenerator{ctrl: ctrl}
	mock.recorder = &MockUniqueIdGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUniqueIdGenerator) EXPECT() *MockUniqueIdGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockUniqueIdGenerator) Generate() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockUniqueIdGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockUniqueIdGenerator)(nil).Generate))
}
